namespace Lexer;

/// <summary>
/// Enumeration representing various types of tokens this lexer
/// returns.
/// </summary>
public enum TokenType
{
    BeginArray,
    BeginObject,
    EndArray,
    EndObject,
    NameSeparator,
    ValueSeparator,
    String,
    Number,
    Boolean,
    Null,
    EOF
}

/// <summary>
/// Token represents an atomic value generated by lexer.
/// </summary>
public class Token
{
    /// <summary>
    /// Type of token represented by this object.
    /// <see cref="TokenType" />
    /// </summary>
    public readonly TokenType Type;

    /// <summary>
    /// Starting byte of this token in the file stream.
    /// </summary>
    public readonly int Start;

    /// <summary>
    /// Ending byte (exclusive) of this token in the file
    /// stream.
    /// </summary>
    public readonly int End;

    public Token(TokenType type, int start, int end)
    {
        this.Type = type;
        this.Start = start;
        this.End = end;
    }
}
